import mongoose from "mongoose";
import { ClothesModel } from "./src/models/clothes.model";
import dotenv from "dotenv";

dotenv.config();

const MONGO_URI = process.env.MONGO_URI || "mongodb://localhost:27017/fashiome-db";

const initialClothes = [

  {
    name: "Sequin Silver Mini Dress",
    category: "party-wear",
    gender: "female",
    size: "S",
    color: "Silver",
    price: 89.99,
    discountedPrice: 74.99,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=600",
    description: "Head-turning silver sequin mini dress with spaghetti straps. The all-over glitter catches every light at the club or a late-night party. Pair with strappy heels.",
    status: "active",
  },
  {
    name: "Gold Glitter Bodycon Dress",
    category: "party-wear",
    gender: "female",
    size: "M",
    color: "Gold",
    price: 95.0,
    discountedPrice: null,
    stock: 18,
    imageUrl: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=600",
    description: "Dazzling gold glitter bodycon midi dress with ruched side detailing and a sweetheart neckline. The ultimate party-night statement piece.",
    status: "active",
  },
  {
    name: "Hot Pink Ruffle Party Dress",
    category: "party-wear",
    gender: "female",
    size: "M",
    color: "Hot Pink",
    price: 72.0,
    discountedPrice: 59.99,
    stock: 25,
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=600",
    description: "Fun, flirty hot pink mini dress with layered ruffle skirt and off-shoulder neckline. A guaranteed crowd-pleaser for birthday parties or bachelorette events.",
    status: "active",
  },
  {
    name: "Midnight Black Sequin Jumpsuit",
    category: "party-wear",
    gender: "female",
    size: "L",
    color: "Black",
    price: 110.0,
    discountedPrice: 89.99,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=600",
    description: "Sleek all-over black sequin jumpsuit with wide-leg silhouette and halter neck. Modern alternative to the party dress — equally glamorous.",
    status: "active",
  },

  {
    name: "Emerald Satin Floor-Length Gown",
    category: "gown",
    gender: "female",
    size: "S",
    color: "Emerald Green",
    price: 195.0,
    discountedPrice: 169.99,
    stock: 10,
    imageUrl: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?q=80&w=600",
    description: "Luxurious floor-length emerald satin gown with a cowl neck and low back. Perfect for galas, black-tie events, and red-carpet occasions.",
    status: "active",
  },
  {
    name: "Dusty Rose Tulle Ball Gown",
    category: "gown",
    gender: "female",
    size: "M",
    color: "Dusty Rose",
    price: 230.0,
    discountedPrice: null,
    stock: 8,
    imageUrl: "https://images.unsplash.com/photo-1518049362265-d5b2a6467637?q=80&w=600",
    description: "Dreamy ball gown with a corseted bodice and voluminous multi-layer dusty rose tulle skirt. Princess silhouette — ideal for proms, weddings, or formals.",
    status: "active",
  },
  {
    name: "Midnight Blue Velvet Column Gown",
    category: "gown",
    gender: "female",
    size: "L",
    color: "Midnight Blue",
    price: 210.0,
    discountedPrice: 185.0,
    stock: 10,
    imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=600",
    description: "Sophisticated column gown in deep midnight blue velvet with a thigh-high slit and bateau neckline. Commands any room at galas or formal dinners.",
    status: "active",
  },
  {
    name: "Ivory Lace Wedding Guest Gown",
    category: "gown",
    gender: "female",
    size: "S",
    color: "Ivory",
    price: 175.0,
    discountedPrice: null,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1584811644165-33078f50eb15?q=80&w=600",
    description: "Elegant ivory lace overlay gown with flutter sleeves and A-line silhouette. Feminine and tasteful for wedding receptions or garden parties.",
    status: "active",
  },

  
  {
    name: "Botanical Floral Wrap Dress",
    category: "streetwear",
    gender: "female",
    size: "M",
    color: "Multi-Floral",
    price: 55.0,
    discountedPrice: 44.99,
    stock: 30,
    imageUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=600",
    description: "Breezy midi wrap dress in a bold botanical floral print. Adjustable tie waist and V-neckline. Perfect for brunch, street style looks, and casual day trips.",
    status: "active",
  },
  {
    name: "Cherry Blossom Floral Mini Skirt",
    category: "skirts",
    gender: "female",
    size: "S",
    color: "Pink & White",
    price: 38.0,
    discountedPrice: null,
    stock: 35,
    imageUrl: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=600",
    description: "Floaty chiffon mini skirt with an all-over cherry blossom print. Wear with a simple crop top for the perfect cottagecore street outfit.",
    status: "active",
  },
  {
    name: "Graphic Oversized Streetwear Hoodie",
    category: "streetwear",
    gender: "female",
    size: "L",
    color: "Washed Black",
    price: 62.0,
    discountedPrice: null,
    stock: 40,
    imageUrl: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?q=80&w=600",
    description: "Premium heavyweight cotton oversized hoodie with bold graphic print. Street-style essential. Pairs with biker shorts, joggers, or mini skirts.",
    status: "active",
  },
  {
    name: "Y2K Butterfly Print Co-ord Set",
    category: "streetwear",
    gender: "female",
    size: "M",
    color: "Purple & White",
    price: 78.0,
    discountedPrice: 65.0,
    stock: 22,
    imageUrl: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=600",
    description: "Retro Y2K inspired butterfly print co-ord set — matching cropped jacket and flare trousers. A statement streetwear look straight from the 2000s.",
    status: "active",
  },

  // ─── FEMALE — FORMAL WEAR ────────────────────────────────────────────────
  {
    name: "Tailored Ivory Power Blazer",
    category: "formal-wear",
    gender: "female",
    size: "M",
    color: "Ivory",
    price: 130.0,
    discountedPrice: 109.99,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=600",
    description: "Sharp structured single-button blazer in ivory crepe. Wide lapels and a longline cut give a powerful boss-woman silhouette. Pairs beautifully with trousers or a pencil skirt.",
    status: "active",
  },
  {
    name: "High-Waist Tailored Wide-Leg Pants",
    category: "formal-wear",
    gender: "female",
    size: "M",
    color: "Charcoal Grey",
    price: 90.0,
    discountedPrice: null,
    stock: 25,
    imageUrl: "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=600",
    description: "Premium charcoal grey high-waisted wide-leg dress pants. Crisp front crease, side zip closure. A wardrobe staple for meetings, interviews, and formal events.",
    status: "active",
  },
  {
    name: "Camel Double-Breasted Wool Coat",
    category: "outerwear",
    gender: "female",
    size: "S",
    color: "Camel",
    price: 199.0,
    discountedPrice: 165.0,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1608234807905-4466023792f5?q=80&w=600",
    description: "Luxuriously crafted double-breasted wool-blend coat in warm camel. Knee-length with a cinched belt. A timeless investment piece for fall and winter.",
    status: "active",
  },
  {
    name: "Satin Blouse — Champagne",
    category: "tops",
    gender: "female",
    size: "S",
    color: "Champagne",
    price: 49.0,
    discountedPrice: null,
    stock: 30,
    imageUrl: "https://images.unsplash.com/photo-1603252109303-2751441dd157?q=80&w=600",
    description: "Silky champagne satin blouse with pearl button closure and flowy sleeves. Transitions effortlessly from boardroom to evening events.",
    status: "active",
  },

  // ─── FEMALE — TRADITIONAL ────────────────────────────────────────────────
  {
    name: "Banarasi Silk Saree — Ruby Red",
    category: "traditional",
    gender: "female",
    size: "OS",
    color: "Ruby Red",
    price: 220.0,
    discountedPrice: 199.99,
    stock: 10,
    imageUrl: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?q=80&w=600",
    description: "Heavy handwoven Banarasi silk saree featuring intricate gold zari brocade work and pallu. The quintessential South Asian formal outfit for weddings and festivals.",
    status: "active",
  },
  {
    name: "Zardozi Purple Anarkali Suit Set",
    category: "traditional",
    gender: "female",
    size: "M",
    color: "Royal Purple",
    price: 155.0,
    discountedPrice: null,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1609357605129-26f69add5d6e?q=80&w=600",
    description: "A gorgeous 3-piece Anarkali suit set in deep royal purple. Features detailed gold zardozi embroidery on the bodice, churidar pants, and a sheer organza dupatta.",
    status: "active",
  },
  {
    name: "Chikankari White Georgette Kurti",
    category: "traditional",
    gender: "female",
    size: "M",
    color: "White",
    price: 49.99,
    discountedPrice: null,
    stock: 35,
    imageUrl: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?q=80&w=600",
    description: "Elegant, lightweight hand-embroidered Lucknowi Chikankari kurti. Flowy silhouette, perfect for hot summer days or casual outings when paired with jeans.",
    status: "active",
  },

  // ─── FEMALE — DRESSES ────────────────────────────────────────────────────
  {
    name: "Floral Georgette Wrap Midi Dress",
    category: "dresses",
    gender: "female",
    size: "S",
    color: "Mint & Floral",
    price: 69.0,
    discountedPrice: 55.0,
    stock: 28,
    imageUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=600",
    description: "Airy georgette wrap midi dress in a fresh mint floral print. The ideal dress for summer weddings, brunches, or a relaxed day out.",
    status: "active",
  },
  {
    name: "LBD — Sleeveless Crepe Midi",
    category: "dresses",
    gender: "female",
    size: "M",
    color: "Black",
    price: 85.0,
    discountedPrice: null,
    stock: 22,
    imageUrl: "https://images.unsplash.com/photo-1518049362265-d5b2a6467637?q=80&w=600",
    description: "The essential little black dress — sleeveless midi in premium stretch crepe with a subtle flare. Effortlessly elegant for dinner, events, or evening outings.",
    status: "active",
  },
  {
    name: "Slip Satin Bias-Cut Maxi Dress",
    category: "dresses",
    gender: "female",
    size: "S",
    color: "Nude",
    price: 99.0,
    discountedPrice: 82.0,
    stock: 18,
    imageUrl: "https://images.unsplash.com/photo-1584811644165-33078f50eb15?q=80&w=600",
    description: "Elegant bias-cut maxi slip dress in nude satin. The figure-skimming silhouette and minimalist design make it perfect for dinner parties or wedding guest outfits.",
    status: "active",
  },

  // ─── FEMALE — ACTIVEWEAR ─────────────────────────────────────────────────
  {
    name: "High-Waist Yoga Leggings — Sage",
    category: "activewear",
    gender: "female",
    size: "M",
    color: "Sage Green",
    price: 52.0,
    discountedPrice: null,
    stock: 40,
    imageUrl: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?q=80&w=600",
    description: "4-way stretch high-waist yoga leggings in sage green. Squat-proof fabric with a hidden waistband pocket. Perfect for gym, yoga, or athleisure.",
    status: "active",
  },
  {
    name: "Sports Bra — Cobalt Blue",
    category: "activewear",
    gender: "female",
    size: "S",
    color: "Cobalt Blue",
    price: 38.0,
    discountedPrice: null,
    stock: 35,
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=600",
    description: "Medium-support sports bra in cobalt blue with a strappy open back. Moisture-wicking fabric keeps you cool during intense workouts.",
    status: "active",
  },

  // ─── MALE — FORMAL WEAR ───────────────────────────────────────────────────
  {
    name: "Classic Navy 2-Piece Suit",
    category: "formal-wear",
    gender: "male",
    size: "L",
    color: "Navy Blue",
    price: 280.0,
    discountedPrice: 239.99,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600",
    description: "Sharp tailored 2-piece suit in navy blue with a subtle herringbone texture. Slim-cut jacket with notched lapels and matching flat-front trousers. For weddings, interviews, and formal events.",
    status: "active",
  },
  {
    name: "Charcoal Slim-Fit Blazer",
    category: "formal-wear",
    gender: "male",
    size: "M",
    color: "Charcoal",
    price: 140.0,
    discountedPrice: 115.0,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=600",
    description: "Premium charcoal slim-fit blazer in a smooth wool blend. Two-button front, slim lapels, and flap pockets. Versatile for smart-casual or fully formal styling.",
    status: "active",
  },
  {
    name: "Ivory Linen Blazer",
    category: "formal-wear",
    gender: "male",
    size: "M",
    color: "Ivory",
    price: 120.0,
    discountedPrice: null,
    stock: 18,
    imageUrl: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=600",
    description: "Relaxed linen blazer in off-white ivory — lightweight and breathable. Perfect for summer weddings, beach events, or smart-casual outings.",
    status: "active",
  },
  {
    name: "Black Dress Trousers",
    category: "formal-wear",
    gender: "male",
    size: "32",
    color: "Black",
    price: 85.0,
    discountedPrice: null,
    stock: 30,
    imageUrl: "https://images.unsplash.com/photo-1506152983158-b4a74a01c721?q=80&w=600",
    description: "Premium slim-fit black dress trousers with a flat front, side pockets, and a subtle stretch for comfort. The backbone of any formal or business wardrobe.",
    status: "active",
  },
  {
    name: "Oxford White Formal Shirt",
    category: "shirts",
    gender: "male",
    size: "M",
    color: "White",
    price: 55.0,
    discountedPrice: null,
    stock: 40,
    imageUrl: "https://images.unsplash.com/photo-1607513543391-45761806cc5d?q=80&w=600",
    description: "Crisp Oxford weave formal shirt in pure white. Slim-fit with a cutaway collar and French cuffs for cufflinks. The ultimate dress shirt for suits and formal occasions.",
    status: "active",
  },
  {
    name: "Burgundy Dress Shirt",
    category: "shirts",
    gender: "male",
    size: "L",
    color: "Burgundy",
    price: 58.0,
    discountedPrice: 48.0,
    stock: 25,
    imageUrl: "https://images.unsplash.com/photo-1542393545-10f5cde2c810?q=80&w=600",
    description: "Rich burgundy stretch dress shirt with a spread collar. Slim fit that complements suits and blazers. A pop of colour for weddings or evening dinners.",
    status: "active",
  },
  {
    name: "Classic Wool Overcoat — Camel",
    category: "outerwear",
    gender: "male",
    size: "L",
    color: "Camel",
    price: 220.0,
    discountedPrice: 185.0,
    stock: 10,
    imageUrl: "https://images.unsplash.com/photo-1608234807905-4466023792f5?q=80&w=600",
    description: "Timeless double-breasted camel wool overcoat with wide notch lapels. Knee-length with side seam pockets. Layers perfectly over suits or smart-casual outfits.",
    status: "active",
  },

  // ─── MALE — PARTY WEAR ────────────────────────────────────────────────────
  {
    name: "Velvet Burgundy Party Blazer",
    category: "party-wear",
    gender: "male",
    size: "M",
    color: "Burgundy",
    price: 135.0,
    discountedPrice: 109.99,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=600",
    description: "Statement velvet blazer in deep burgundy. Slim lapels with satin trim. Wear over a white shirt for a party-ready look that is elevated but not overdressed.",
    status: "active",
  },
  {
    name: "Embroidered Satin Party Shirt",
    category: "party-wear",
    gender: "male",
    size: "M",
    color: "Midnight Blue",
    price: 79.0,
    discountedPrice: null,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1542393545-10f5cde2c810?q=80&w=600",
    description: "Midnight blue satin shirt with subtle tonal embroidery on the chest. Open collar, slightly loose fit. The perfect party shirt for a night out.",
    status: "active",
  },

  // ─── MALE — STREETWEAR ────────────────────────────────────────────────────
  {
    name: "Premium Graphic Tee — Black",
    category: "streetwear",
    gender: "male",
    size: "L",
    color: "Black",
    price: 40.0,
    discountedPrice: null,
    stock: 50,
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=600",
    description: "Heavyweight 230gsm cotton graphic tee with a bold exclusive print. Oversized boxy fit for the perfect streetwear silhouette.",
    status: "active",
  },
  {
    name: "Cargo Joggers — Olive",
    category: "streetwear",
    gender: "male",
    size: "M",
    color: "Olive",
    price: 65.0,
    discountedPrice: 54.99,
    stock: 35,
    imageUrl: "https://images.unsplash.com/photo-1506152983158-b4a74a01c721?q=80&w=600",
    description: "Relaxed-fit cargo joggers in olive twill with a drawstring waist and cargo side pockets. Street-ready comfort meets utility.",
    status: "active",
  },
  {
    name: "Varsity Bomber Jacket — Black & Red",
    category: "outerwear",
    gender: "male",
    size: "L",
    color: "Black & Red",
    price: 115.0,
    discountedPrice: null,
    stock: 22,
    imageUrl: "https://images.unsplash.com/photo-1547036967-23d11aacaee0?q=80&w=600",
    description: "Classic varsity-style bomber jacket with black body, red stripes, and ribbed collar. Premium satin lining and chenille patch details. Streetwear staple.",
    status: "active",
  },
  {
    name: "Washed Denim Jacket",
    category: "outerwear",
    gender: "male",
    size: "M",
    color: "Acid Wash Blue",
    price: 88.0,
    discountedPrice: 74.0,
    stock: 28,
    imageUrl: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=600",
    description: "Classic acid-washed denim jacket with a slightly oversized cut. Timeless layering piece for streetwear, casual, or smart-casual outfits.",
    status: "active",
  },

  // ─── MALE — TRADITIONAL ───────────────────────────────────────────────────
  {
    name: "Indigo Block-Print Cotton Kurta",
    category: "traditional",
    gender: "male",
    size: "L",
    color: "Indigo",
    price: 39.99,
    discountedPrice: 34.99,
    stock: 40,
    imageUrl: "https://images.unsplash.com/photo-1607513543391-45761806cc5d?q=80&w=600",
    description: "Traditional hand-block printed indigo blue long kurta in 100% breathable cotton. Classic band collar, perfect for casual and semi-formal wear.",
    status: "active",
  },
  {
    name: "Raw Silk Mustard Kurta",
    category: "traditional",
    gender: "male",
    size: "M",
    color: "Mustard",
    price: 65.0,
    discountedPrice: null,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1597983073493-88cd35cf93b0?q=80&w=600",
    description: "Premium raw silk kurta in rich mustard yellow. Structured neckline and clean seams. Ideal for festive gatherings, puja, and wedding events.",
    status: "active",
  },
  {
    name: "Embellished Silk Nehru Jacket",
    category: "traditional",
    gender: "male",
    size: "L",
    color: "Navy Blue",
    price: 85.0,
    discountedPrice: 75.0,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=600",
    description: "Royal navy blue silk Nehru jacket with subtle gold thread embroidery and brass buttons. Adds an instant ethnic touch to kurtas or formal shirts.",
    status: "active",
  },

  // ─── MALE — ACTIVEWEAR ───────────────────────────────────────────────────
  {
    name: "Compression Training Tights — Slate",
    category: "activewear",
    gender: "male",
    size: "M",
    color: "Slate Grey",
    price: 55.0,
    discountedPrice: null,
    stock: 30,
    imageUrl: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?q=80&w=600",
    description: "High-performance compression training tights in slate grey. 4-way stretch, moisture-wicking, and flatlock seams prevent chafing during intense gym sessions.",
    status: "active",
  },
  {
    name: "Dry-Fit Running Vest — Electric Blue",
    category: "activewear",
    gender: "male",
    size: "L",
    color: "Electric Blue",
    price: 38.0,
    discountedPrice: 29.99,
    stock: 35,
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=600",
    description: "Lightweight ultra-breathable dry-fit running vest in electric blue. Reflective strips for outdoor runs. Ergonomic cut for maximum range of motion.",
    status: "active",
  },

  // ─── UNISEX — SHOES ──────────────────────────────────────────────────────
  {
    name: "Chunky White Sneakers",
    category: "shoes",
    gender: "unisex",
    size: "40",
    color: "White",
    price: 85.0,
    discountedPrice: null,
    stock: 18,
    imageUrl: "https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=600",
    description: "Sporty chunky sneakers in crisp white. A streetwear classic that pairs with anything from joggers to floral dresses.",
    status: "active",
  },
  {
    name: "Clean Leather Loafers — Black",
    category: "shoes",
    gender: "unisex",
    size: "42",
    color: "Black",
    price: 90.0,
    discountedPrice: 79.99,
    stock: 15,
    imageUrl: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?q=80&w=600",
    description: "Sleek leather loafers in polished black. Pairs with trousers, chinos, or raw silk kurtas for a clean smart look.",
    status: "active",
  },
  {
    name: "Embroidered Gold Juttis",
    category: "shoes",
    gender: "female",
    size: "38",
    color: "Gold",
    price: 49.99,
    discountedPrice: 42.99,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1562273138-f46be4ebdf33?q=80&w=600",
    description: "Handcrafted pure leather Juttis with golden thread embroidery, sequin embellishments, and padded soles. Perfect for finishing ethnic and Indo-Western looks.",
    status: "active",
  },

  // ─── UNISEX — ACCESSORIES ────────────────────────────────────────────────
  {
    name: "Minimalist Gold Chain Necklace",
    category: "accessories",
    gender: "female",
    size: "OS",
    color: "Gold",
    price: 28.0,
    discountedPrice: null,
    stock: 50,
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600",
    description: "Delicate 18k gold-plated chain necklace with a subtle pendant. Pairs perfectly with party dresses, gowns, or a simple white tee.",
    status: "active",
  },
  {
    name: "Structured Minimal Tote — Black",
    category: "accessories",
    gender: "unisex",
    size: "OS",
    color: "Black",
    price: 110.0,
    discountedPrice: 99.99,
    stock: 12,
    imageUrl: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?q=80&w=600",
    description: "Large capacity structured premium leather tote bag. Ideal for carrying notebooks, tablets, and daily travel essentials.",
    status: "active",
  },
  {
    name: "Kundan Chandbali Earrings",
    category: "accessories",
    gender: "female",
    size: "OS",
    color: "Gold",
    price: 29.99,
    discountedPrice: null,
    stock: 50,
    imageUrl: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=600",
    description: "Stunning gold-plated Chandbali earrings decorated with Kundan stones and tiny white pearls. A statement ethnic accessory.",
    status: "active",
  },
  {
    name: "Silver Watch — Minimalist Mesh",
    category: "accessories",
    gender: "male",
    size: "OS",
    color: "Silver",
    price: 95.0,
    discountedPrice: 79.0,
    stock: 20,
    imageUrl: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=600",
    description: "Sleek minimalist watch with a silver mesh strap and clean white dial. The subtle luxury accessory to complete any formal or smart-casual outfit.",
    status: "active",
  },
];

async function seedData() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("Connected to MongoDB for seeding...");

    // Delete existing clothes to prevent duplicate mock data
    await ClothesModel.deleteMany({});
    console.log("Cleared existing clothes collection.");

    // Seed data
    const inserted = await ClothesModel.insertMany(initialClothes);
    console.log(`\nSuccessfully seeded ${inserted.length} clothing items!`);
    console.log(`  Female items: ${initialClothes.filter(i => i.gender === "female").length}`);
    console.log(`  Male items:   ${initialClothes.filter(i => i.gender === "male").length}`);
    console.log(`  Unisex items: ${initialClothes.filter(i => i.gender === "unisex").length}`);

    process.exit(0);
  } catch (error) {
    console.error("Seeding failed:", error);
    process.exit(1);
  }
}

seedData();
